//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUrunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUrunler()
        {
            this.TBLSatıs = new HashSet<TBLSatıs>();
        }
    
        public int urunId { get; set; }
        public string urunAd { get; set; }
        public Nullable<short> urunKategori { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string marka { get; set; }
        public Nullable<byte> stok { get; set; }
    
        public virtual TBLKategoriler TBLKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSatıs> TBLSatıs { get; set; }
    }
}
